name: 'drought_transformations'
version: '1.0.0'
config-version: 2

profile: 'athena_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"

models:
  drought_transformations:
    +materialized: table
